module.exports = {
  svgoConfig: './.svgo.yml',
  multipass: true,
  plugins: {
    addAttributesToSVGElement: false,
    addClassesToSVGElement: true,
    cleanupAttrs: true,
    cleanupEnableBackground: true,
    cleanupIDs: false,
    cleanupListOfValues: true,
    cleanupNumericValues: true,
    floatPrecision: 2,
    collapseGroups: true,
    convertColors: true,
    convertPathData: true,
    convertShapeToPath: true,
    convertStyleToAttrs: true,
    convertTransform: true,
    mergePaths: true,
    minifyStyles: true,
    moveElemsAttrsToGroup: true,
    moveGroupAttrsToElems: true,
    removeAttrs: true,
    removeComments: true,
    removeDesc: true,
    removeDimensions: true,
    removeDoctype: true,
    removeEditorsNSData: true,
    removeElementsByAttr: true,
    removeEmptyAttrs: true,
    removeEmptyContainers: true,
    removeEmptyText: true,
    removeHiddenElems: true,
    removeMetadata: true,
    removeNonInheritableGroupAttrs: true,
    removeRasterImages: false,
    removeStyleElement: true,
    removeTitle: true,
    removeUnknownsAndDefaults: true,
    removeUnusedNS: true,
    removeUselessDefs: true,
    removeUselessStrokeAndFill: true,
    removeViewBox: false,
    removeXMLNS: false,
    removeXMLProcInst: true,
    sortAttrs: true,
    transformsWithOnePath: true,
  },

  js2svg: {
    pretty: true,
    indent: '  ',
  },
};
